//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int Ma_Ad { get; set; }
        public string Name_Ad { get; set; }
        public string Mail { get; set; }
        public string Password { get; set; }
    }
}
