//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int Ma_FB { get; set; }
        public string Ten { get; set; }
        public string SDT { get; set; }
        public string Mail { get; set; }
        public string Content { get; set; }
        public System.DateTime Created { get; set; }
    }
}
