//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.DetailOrders = new HashSet<DetailOrder>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int Ma_Order { get; set; }
        public Nullable<int> Ma_Mem { get; set; }
        public Nullable<double> Total { get; set; }
        public string Shipping { get; set; }
        public System.DateTime Created { get; set; }
        public string Note { get; set; }
        public string Ten_NguoiNhan { get; set; }
        public string DiaChi_NguoiNhan { get; set; }
        public string SDT__NguoiNhan { get; set; }
        public string Mail_NguoiNhan { get; set; }
        public string TP_NguoiNhan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailOrder> DetailOrders { get; set; }
        public virtual Member Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
