//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.DetailOrders = new HashSet<DetailOrder>();
        }
    
        public int Ma_Product { get; set; }
        public int Ma_Brand { get; set; }
        public int Ma_Type { get; set; }
        public string Ten_Product { get; set; }
        public string Ten_Alias { get; set; }
        public int Gia_Product { get; set; }
        public string Info_Product { get; set; }
        public int Available { get; set; }
        public string Image_Product { get; set; }
        public string Detail_Product { get; set; }
        public string Describe_Product { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailOrder> DetailOrders { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual Type Type { get; set; }
    }
}
