//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Ma_Tran { get; set; }
        public int Ma_Order { get; set; }
        public int Status { get; set; }
        public double Total { get; set; }
        public string Note { get; set; }
        public string Payment { get; set; }
        public string Payment_Info { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
